### ISSUE TITLE
Can't pass custom device_map to lmql serve_model with --cuda

### ISSUE THREAD

**Issue by bglazer** [eth-sri/lmql#114]
Starting an LMQL server with `lmql serve-model ... --cuda` invokes `lmql.models.lmtp.lmtp_serve`. This function calls `lmql.models.lmtp.utils.rename_model_args` which has the following line:

`if cuda:
        model_args["device_map"] = "auto"`

This automatically re-assigns the "device_map" parameter to "auto", even if I pass a custom value. 

I have a model that fits on a single GPU, so there's no need to distribute it across multiple GPU's. To improve latency I would prefer to specify `device_map: 0` so that the model is loaded on a single GPU.

**Comment by lbeurerkellner** [comment]
Thanks for raising this. This should definitely be fixed. For now I can recommend the use of `CUDA_VISIBLE_DEVICES=0` as a workaround that should limit distribution to only GPU 0.

**Comment by lbeurerkellner** [comment]
The original issue should also be fixed in the release that just got pushed to pypi.org, 0.0.6.5.
