### ISSUE TITLE
LMQL in Python using llama.cpp - cannot use multiple tokenizers in the same process for now

### ISSUE THREAD

**Issue by SlistInc** [eth-sri/lmql#134]
I am happily using LMQL using the playground. I am actually using it with a local model / llama.cpp and that works very well. However I get an error when trying to use LMQL in python. I suspect this is related to the llama.cpp implementation.

Here is the code (from https://docs.lmql.ai/en/stable/python/python.html) I try to run:
`import lmql
import asyncio

@lmql.query
async def hello():
    '''lmql
    argmax
        "Hello[WHO]"
        return WHO
    from
        "llama.cpp:/SOME_PATH_TO_LOCAL_MODEL/wizard-vicuna-7b-uncensored-superhot-8k.ggmlv3.q4_K_M.bin"
    where
        len(TOKENS(WHO)) < 10
    '''
await asyncio.gather(*[hello() for _ in range(1)])`

I am getting this error:

`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[22], line 17
      6     '''lmql
      7     argmax
      8         "Hello[WHO]"
   (...)
     13         len(TOKENS(WHO)) < 10
     14     '''
     16 # run 10 instances of 'hello' in parallel
---> 17 await asyncio.gather(*[hello() for _ in range(1)])

File /opt/homebrew/Caskroom/miniforge/base/envs/python3.10/lib/python3.10/site-packages/lmql/runtime/lmql_runtime.py:213, in LMQLQueryFunction.__acall__(self, *args, **kwargs)
    210     query_kwargs["__self__"] = query_kwargs.pop("self")
    212 # execute main prompt
--> 213 results = await interpreter.run(self.fct, **query_kwargs)
    215 # applies distribution postprocessor if required
    216 results = await (ConditionalDistributionPostprocessor(interpreter).process(results))

File /opt/homebrew/Caskroom/miniforge/base/envs/python3.10/lib/python3.10/site-packages/lmql/runtime/interpreter.py:719, in PromptInterpreter.run(self, fct, *args, **kwargs)
    717 decoder_args = self.decoder_kwargs
    718 self.model.decoder_args = decoder_args
--> 719 self.dcmodel: dc.DcModel = self.model.get_dclib_model()
    721 # handle queries w/o any TemplateVariables
    722 if self.root_state.query_head.result is not None:

File /opt/homebrew/Caskroom/miniforge/base/envs/python3.10/lib/python3.10/site-packages/lmql/models/lmtp/lmtp_dcmodel.py:440, in lmtp_model.__call__.<locals>.LMTPModelCls.get_dclib_model(self)
    437 bos_token_id = self.get_tokenizer().bos_token_id
    438 eos_token_id = self.get_tokenizer().eos_token_id
--> 440 dc.set_dclib_tokenizer(self.get_tokenizer())
    442 inprocess_client_constructor = None
    444 if this.inprocess:

File /opt/homebrew/Caskroom/miniforge/base/envs/python3.10/lib/python3.10/site-packages/lmql/runtime/dclib/dclib_global.py:15, in set_dclib_tokenizer(tokenizer)
     14 def set_dclib_tokenizer(tokenizer):
---> 15     assert DcGlobal.tokenizer is None or DcGlobal.tokenizer.name == tokenizer.name, f"Cannot set dclib tokenizer to {tokenizer.name} because it is already set to {DcGlobal.tokenizer.name} (cannot use multiple tokenizers in the same process for now)"
     16     DcGlobal.tokenizer = tokenizer

AssertionError: Cannot set dclib tokenizer to hf-huggyllama/llama-7b because it is already set to tiktoken-gpt2 (cannot use multiple tokenizers in the same process for now)`

Consider that the LMQL code works well in the playground.

Am I doing anything wrong or is there an issue with the llama.cpp implementation?

**Comment by SlistInc** [comment]
Thanks for your feedback!

I tried the reinstall as proposed. I have an interesting observation that I didn't properly test before. Here is the behaviour I observe:

- **Running in LMQL Playground:** works
- **Running as plain python code:** works
- **Running code in jupyter notebook:** AssertionError: LMQL queries cannot be called synchronously from within an async context. Please use async queries and await them instead.

So when I reported the issue I only ran it in a jupyter notebook. It seems related to that. It's probably the way Jupyter handles the async stuff.

I'm fine with working in a python IDE but maybe it could be useful for newbies to be aware of this issue.

**Comment by lbeurerkellner** [comment]
In Jupyter, it should generally work simply by calling `await` on the top-level, e.g.:

```
await query()
```

What you can't do, and this is where you have to be careful with Jupyter, is mixing two models in the same Python process (cf. error message).

If somewhere in the same Notebook you used a GPT-based model, this counts as mixing models. Restart the kernel to avoid this. We want to support multi-model use, but this needs some removing of a global state, so for now it is not supported. Let me know if this works.

**Comment by SlistInc** [comment]
Sorry, my mistake. I ran the wrong code snippet before. I ran the async code example and I can report that it works after the update you proposed. It was not an issue of different models for sure.

So I guess the `pip install lmql[hf]` fixed it. You can close this issue, thanks a lot for the support.

**Comment by lbeurerkellner** [comment]
Awesome, thanks for reporting it. I'll make sure to add a note and error message, if people miss installing with `lmql[hf]` for `llama.cpp` use.
