### ISSUE TITLE
STOPS_AT constraint doesn't work as expected

### ISSUE THREAD

**Issue by ChezzPlaya** [eth-sri/lmql#144]
Given the following script:

```python
import lmql


@lmql.query
def linguistic_test():
    '''lmql

    import lmql

    argmax
        "### System:\n"
        "You are an excellent linguist.\n\n"

        "### User:\n"
        "What is the verb, object and argument of the following utterance: Increase the bass level by 10%.\n\n"


        "### Assistant:\n"
        "- Verb: [VERB]\n"
        "- Object: [OBJECT]\n" 
        "- Argument: [ARGUMENT]\n"

    from
        lmql.model("stabilityai/StableBeluga-7B", endpoint='localhost:9000')
    where 
        STOPS_AT(ARGUMENT, "\n")
    
    '''

print(linguistic_test()[0].prompt)
```

I get the following output from the llm:

```
### System:
You are an excellent linguist.

### User:
What is the verb, object and argument of the following utterance: Increase the bass level by 10%.

### Assistant:
- Verb:  increase
- Object: the bass level
- Argument: 10%
- Object: 10%
- Argument: 10%

```

As it can be seen, the LLM doesn't stop at the ARGUMENT although the new line character has been generated.

Here, I'm using the following model:

`lmql serve-model "stabilityai/StableBeluga-7B" --cuda --port 9000 --dtype "8bit" --top_p 0.95 --temperature 0.01`

**Comment by 4onen** [comment]
StableBeluga is a LLaMA 2 model, so is this the LLaMA2 tokenizer bug again?

**Comment by lbeurerkellner** [comment]
Yes, the Llama-2 tokenizer is currently not fully supported for constrained decoding (see also https://github.com/eth-sri/lmql/issues/155).

**Comment by lbeurerkellner** [comment]
Llama-2 tokenizer support has now landed on 'main' and query code above should run as expected. Llama-2 support will be part of the next release.

**Comment by ChezzPlaya** [comment]
@lbeurerkellner I tried the code with the latest main branch installed. It's still not running correctly.

**Comment by lbeurerkellner** [comment]
As per the 0.7 release, this has arrived on the stable channel of LMQL.

**Comment by lbeurerkellner** [comment]
As per the 0.7 release, Llama-2 support has arrived on the stable channel of LMQL.
