### ISSUE TITLE
[Error during generate()] Could not broadcast input array from shape

### ISSUE THREAD

**Issue by klutzydrummer** [eth-sri/lmql#148]
I have lmql code that works in the playground but fails when running in Google co-lab with the following from statement: "local:llama.cpp:/content/Machine_Learning_Digestor/models/stablebeluga-7b.ggmlv3.q4_1.bin"

I can see that python code embedded in the lmql does run and it does at least appear to be actually inferencing, but I get this error every time I try to run it:

---

```
[Loading llama.cpp model from llama.cpp:/content/Machine_Learning_Digestor/models/stablebeluga-7b.ggmlv3.q4_1.bin  with  {} ]
[Error during generate()] could not broadcast input array from shape (159,) into shape (0,)
```

---

```
[/usr/local/lib/python3.10/dist-packages/lmql/models/lmtp/lmtp_multiprocessing.py](https://localhost:8080/#) in stream_iterator(self, stream_id)
    174 
    175             if item.get("error") is not None:
--> 176                 raise LMTPStreamError(item["error"])
    177 
    178             if item.get("finish_reason") is not None:

LMTPStreamError: failed to generate tokens 'could not broadcast input array from shape (159,) into shape (0,)'
```

---

I've tried to run:
`lmql serve-model "llama.cpp:/content/Machine_Learning_Digestor/models/stablebeluga-7b.ggmlv3.q4_1.bin"`
in the event that maybe there's just some misuse of the library on my part, but this gives me this error:

---

`cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)`

---

Same error as this issue: https://github.com/eth-sri/lmql/issues/117

Ultimately, I haven't had much luck getting any Llama model running with lmql. Is there something that I am missing in my from statement or missing from the docs?

**Comment by lbeurerkellner** [comment]
This error message typically comes from llama-cpp-python if your prompt exceeds the n_ctx context length. Can you try with `lmql.model("local:llama.cpp:...", n_ctx=2048)`.

`lmql serve-model` is currently not supported on Google Colab, the in-process loading as shown [here](https://colab.research.google.com/drive/154xVFkGL54sn7gMEO57G-eOQkbkHWiCZ?usp=sharing), should be possible.

**Comment by klutzydrummer** [comment]
Ah thank you for your help, it does appear that was the trick to it!
