### ISSUE TITLE
Discord link in docs is broken

### ISSUE THREAD

**Issue by dtch1997** [eth-sri/lmql#151]
When I click on the Discord link, I get this error message
![image](https://github.com/eth-sri/lmql/assets/25474937/445006dc-43d2-4675-8b8e-c4a04013e6e1)

**Comment by lbeurerkellner** [comment]
Just tried in private browsing and I was able to through the registration process. Does this link also not work for you: https://discord.com/invite/7eJP4fcyNT ?

**Comment by dtch1997** [comment]
The link works! I realized I couldn't join because I had hit the Discord server limit (contrary to online documentation,  it is much less than 100 - about 20 or so for me). 

Thanks!
