### ISSUE TITLE
Getting strange outputs when using LMQL with llama.cpp 

### ISSUE THREAD

**Issue by reuank** [eth-sri/lmql#154]
I'm trying to run LMQL with an OpenLlama model via llama.cpp on a device with an Apple Silicon chip.

I got everything to work independently:
- The model itself seems to work just fine (verified it by running llama.cpp examples and getting sensible outputs)
- Running `lmql serve-model` works
- Running `lmql playground` works

However, when I try to run some LMQL examples in the playground, I get very strange outputs:
<img width="750" alt="image" src="https://github.com/eth-sri/lmql/assets/6730567/8d9364f3-81f5-4025-a756-fcc08a9bcaa2">

I don't get any errors, neither in the playground, nor in the `lmql serve-model` process.

Any idea what could be the problem here?

**Comment by lbeurerkellner** [comment]
The reason for this is that OpenLlama uses a different tokenizer than standard llama, but we assume all llama.cpp models to rely on the original Llama tokenizer. So you are generating text with OpenLlama but decoding the IDs with the standard Llama tokenizer.

Can you try to run with `lmql.model("llama.cpp:...", tokenizer="danielhanchen/open_llama_3b")`. There were also some issue with early OpenLlama tokenizers as discussed here: https://github.com/eth-sri/lmql/issues/98#issuecomment-1637787086.

**Comment by reuank** [comment]
Thank you for your answer!

Unfortunately, this didn't solve the problem. When looking at the code, I found that this line is overwriting any tokenizer information when using llama.cpp:
https://github.com/eth-sri/lmql/blob/f6f8c0c4b43140c8d07e3bb8cb975aa5f02a42f9/src/lmql/models/model.py#L47

It should instead be something like:
```python
kwargs["tokenizer"] = kwargs.get("tokenizer", "huggyllama/llama-7b")
```

With this change, the specified tokenizer gets downloaded into the cache and used during inference, which leads to sensible output. 

I will open a PR to fix this later.

**Comment by lbeurerkellner** [comment]
This has been addressed by offering the option to configure the tokenizer. In the future we also want to support llama.cpp's own tokenizer #162 and we could also be a bit smarter about automatically choosing a good HF tokenizer for a given llama.cpp model. However, as for this issue, I would consider this closed. Thanks again for your contribution.
