### ISSUE TITLE
Conditions incorrect in Llama2 ("Yes" vs " Yes")

### ISSUE THREAD

**Issue by fjfricke** [eth-sri/lmql#155]
I guess this has to do with the token for some words starts with a space and is not just an issue with LLama2, but when conditioning the output to be e.g. "Yes" and "No" in Llama2, the output may also be " Yes" or " No". This is not very practical for if clauses or further processing.

Example:

```
@lmql.query
async def test():
    '''lmql
    argmax
    "Given a university description, tell me whether it contains the following information:\n"
    "Description: ETH Zurich in Zürich, Switzerland. Founded by the Swiss federal government in 1854, it was modeled on the École polytechnique in Paris, with the stated mission to educate engineers and scientists\n"
    "Is the founded year information present? [PRESENT]\n" where PRESENT in set(["Yes", "No"])
    print(PRESENT)
    if PRESENT == " Yes":
      "If yes, copy the shortest possible snippet in quotation marks from the description that contains the founded year information: '[PHRASE]'\n" where STOPS_BEFORE(PHRASE, "'")
    from
        lmql.model('meta-llama/Llama-2-7b-hf', endpoint="localhost:8095")
        # lmql.model('openai/text-davinci-003')
    '''

(await test())[0].prompt
```
```
print(PRESENT)
" YES"
```

**Comment by lbeurerkellner** [comment]
There is currently a whitespace issue with the llama-2 tokenizer, which behaves differently from llama-1. E.g. for `huggyllama/llama-7b`  the query executes as expected. This can lead to unexpected behaviour with constraints, I am already investigating this.

**Comment by lbeurerkellner** [comment]
Llama-2 tokenizer support has now landed on 'main' and query code above should run as expected. Llama-2 support will be part of the next release.

**Comment by lbeurerkellner** [comment]
As per 0.7, this functionality has been released to the stable channel.
