### ISSUE TITLE
The operation InOpStrInSet does not output the expected content.

### ISSUE THREAD

**Issue by zhangyuhanjc** [eth-sri/lmql#159]
# Description of the problem:
The operators InOps / InOpStrInSet are not outputting the expected content. It seems that while these operators work correctly for the llama1 model, they output incorrect results for the llama2 model.
# For example:
In llama-7b

```
argmax(chunksize=1)
    """
    hi,[CONTENT]
    """
from 
    lmql.model("llama-7b-hf", cuda=True, trust_remote_code=True,load_in_8bit=True,endpoint="localhost:8081") 
where 
    CONTENT in set(['how are you', 'i am a robot'])
```
we got the following results, which is correct.
[LMQLResult(prompt='\nhi,i am a robot\n', variables={'CONTENT': 'i am a robot'}, distribution_variable=None, distribution_values=None)]

However In Llama-2-7b
```
argmax(chunksize=1)
    """
    hi,[CONTENT]
    """
from 
    lmql.model("Llama-2-7b-hf", cuda=True, trust_remote_code=True,load_in_8bit=True,endpoint="localhost:8081") 
where 
    CONTENT in set(['how are you', 'i am a robot'])
```
we got  the following results, which is incorrect.
[LMQLResult(prompt='\nhi, i\n', variables={'CONTENT': ' i'}, distribution_variable=None, distribution_values=None)]

# Possible reasons:
I speculate that this specific handling in hf_tokenizer.py for the llama tokenizer may not be applicable to llama2.
This section of code in hf_tokenizer.py is specifically tailored for the llama tokenizer, but it may not be applicable for llama2.
```
def __call__(self, text_or_list, add_special_tokens=False):
    text_or_list = self.tokenizer.bos_token + text_or_list
    result = super().__call__(text_or_list, add_special_tokens=add_special_tokens)
    result["input_ids"] = result["input_ids"][1:]
    return result
```

I guess for the sentence "i am a robot", the tokenizer in llama2 believes that there is a space between '\<s>' and ‘i’. This causes the InOpStrInSet operator to not recognize the  '  i' in the string 'i am a robot' when calculating suffix, which leads to the termination of the InOpStrInSet calculation and only outputs variables={'CONTENT': ' i'}.

Here are some references for the differences between the two tokenizer models that might help better understand the possible reasons for this case.
llama-7b
```
tokenizer_llama("<s>i am a robot",add_special_tokens=False) # [1, 29875, 626, 263, 19964]
tokenizer_llama.convert_ids_to_tokens([1, 29875, 626, 263, 19964]) # ['<s>', 'i', '▁am', '▁a', '▁robot']
tokenizer_llama.decode([1,29875, 626, 263, 19964]) # '<s>i am a robot'
```
llama-2-7b
```
tokenizer_llama2("<s>i am a robot",add_special_tokens=False) # [1, 474, 626, 263, 19964]
tokenizer_llama2.convert_ids_to_tokens([1, 474, 626, 263, 19964]) # ['<s>', '▁i', '▁am', '▁a', '▁robot']
tokenizer_llama2.decode([1, 474, 626, 263, 19964]) # '<s> i am a robot'
```

# Possible solutions:
I haven't thought of any yet.

**Comment by lbeurerkellner** [comment]
Thanks for reporting this. The Llama-2 tokenizer behaves a bit differently from Llama-1, which needs some different handling on our end when it comes to whitespace (see also e.g. #155). I am working on a fix, with the WIP happening on `llama-2-tokenizer`.

**Comment by lbeurerkellner** [comment]
Llama-2 tokenizer support has now landed on 'main' and query code above should run as expected. Llama-2 support will be part of the next release.

**Comment by zhangyuhanjc** [comment]
> Llama-2 tokenizer support has now landed on 'main' and query code above should run as expected. Llama-2 support will be part of the next release.

Thank you very much for this update support，it's really great, I have to admit that this project has a very high update efficiency.
