### ISSUE TITLE
minimal example for inference-as-a-service

### ISSUE THREAD

**Issue by shijie-wu** [eth-sri/lmql#16]
Congrats on this amazing project! We are interested in testing LMQL for inference-as-a-service. It would be great if the document contains a minimal example of using LMQL as library that
1. load a HF model once
2. handle LMQL as string

**Comment by lbeurerkellner** [comment]
Thank you for this inquiry. Both 1+2 are possible, I will try to soon add an appropriate sample to the documentation.

**Comment by shijie-wu** [comment]
@lbeurerkellner do you have any update on this? thanks!

**Comment by shijie-wu** [comment]
thanks so much!!!
