### ISSUE TITLE
Question about the implementation of `stops_at`

### ISSUE THREAD

**Issue by weilong-web** [eth-sri/lmql#160]
Could you please provide a comprehensive explanation of the underlying theory that governs the concept of 'stop_at'? In cases where 'stop_at' is employed to ascertain the absence of specific characters at the conclusion of a sequence, what are the potential consequences and implications of such an evaluation? Furthermore, should 'stop_at' identify the presence of said characters, does it subsequently prompt a modification in its querying approach, leading to a repetition of the inquiry process? If indeed such a repetition occurs, I am curious to know the precise nature of the revised prompt that would be presented.

**Comment by lbeurerkellner** [comment]
`stops_at` merely serves as stopping criterion and simply forces an end to text generation once the stopping phrase is encountered. It does not remove the phrase nor does it prevent the phrase from being generated. We also do not re-query the model to enforce constraints, but rather pro-actively mask its token distribution.

I hope this answers your question. If not, please let me know, I am happy to discuss further.
