### ISSUE TITLE
Nucleus Sampling

### ISSUE THREAD

**Issue by MiladInk** [eth-sri/lmql#174]
Hi! 

Thanks for the great project. I am wondering if this is possible to add nucleus sampling to the project?
I am asking this because it is the most used mode of decoding I believe. 

Cheers.

**Comment by lbeurerkellner** [comment]
Thanks for the suggestion. It is definitely something we should support. I will keep this issue as a feature tracker.

**Comment by lbeurerkellner** [comment]
As per https://github.com/eth-sri/lmql/issues/227 and the 0.7 release, LMQL now support top_p/nucleus sampling (HF and llama.cpp). OpenAI does not offer this option for their models, unfortunately.
