### ISSUE TITLE
How to force serve-model to load llama.cpp on the GPU?

### ISSUE THREAD

**Issue by Sharrp** [eth-sri/lmql#177]
Hello.

Launching llama.cpp locally with the command below loads the model on the GPU (evident by GPU utilisation):
`./main -m {path to model's .bin file} --temp 1 -ngl 1 -p "{some prompt}"`

At the same time making the model available through serve-model utilizes CPU:
`lmql serve-model llama.cpp:{path to model's .bin file} --n_ctx 2048`

Adding `--cuda` parameter results in:
`File "/opt/homebrew/lib/python3.11/site-packages/lmql/models/lmtp/backends/llama_cpp_model.py", line 21, in __init__
    self.llm = Llama(model_path=model_identifier[len("llama.cpp:"):], **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Llama.__init__() got an unexpected keyword argument 'device_map'`

Adding `--ngl 1` parameter results in:
`File "/opt/homebrew/lib/python3.11/site-packages/lmql/models/lmtp/backends/llama_cpp_model.py", line 21, in __init__
    self.llm = Llama(model_path=model_identifier[len("llama.cpp:"):], **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Llama.__init__() got an unexpected keyword argument 'ngl'`

Could you please help me understand how to serve the model loaded on the GPU?

**Comment by lbeurerkellner** [comment]
I think the `--ngl` parameter is a short-hand for `--n_gpu_layers`, which is what I use with `serve-model` to run with llama.cpp on GPU. We use llama-cpp-python, which only seems to support the long form.

**Comment by Sharrp** [comment]
Thank you!

It's better in a sense that server starts but the model still loads on the CPU:
`lmql serve-model llama.cpp:{path to model's .bin file} --n_ctx 2048 --n_gpu_layers 1`

I'm curious what else is there to try.

**Comment by lbeurerkellner** [comment]
Did you install llama-cpp-python with CUDA support?

**Comment by Sharrp** [comment]
No, missed that part. Thank you for clarifying.
I faced some issues during the installation and will make another attempt at resolving them.
