### ISSUE TITLE
Live Playground: Pass prompt via url variable?

### ISSUE THREAD

**Issue by ggbetz** [eth-sri/lmql#180]
Hello!

Thanks & congrats for setting up this wonderful tool!

Is it possible to pass a prompt to the playground via a url variable? Roughly like, e.g., 

`https://lmql.ai/playground?prompt=""argmax %22One line is all it takes [CONTINUATION]%22 from %22openai/text-davinci-003%22"`

If not, could you indicate what it would take to implement this feature?

I think that would be extremely useful, as you could then have links like "Open in LMQL Playground" basically from anywhere.

Best,
Gregor

**Comment by lbeurerkellner** [comment]
Hi Gregor,

Indeed, this is possible, however, you have to use GitHub Gists for it. For instance, you can visit the following link, to load an LMQL file from my Gists profile:

https://lmql.ai/playground/?snippet=gist:lbeurerkellner/ba9723b1d784ff3e3f9247e02939d9b3/raw/test.lmql


This URL is constructed as follows

```
https://lmql.ai/playground/?snippet=gist:<GITHUB_USER>/<GIST_ID>/raw/<file>.lmql
``` 

Note: Sometimes when updating a Gist, it may take a while to propagate through all the caches, leading to the playground loading an outdated version for a while still.

**Comment by lbeurerkellner** [comment]
I thought about passing it by URL as well, but the character limit will kick in at some point. Still, happy to accept PRs that add more options to pull in LMQL code. The relevant file is here: https://github.com/eth-sri/lmql/blob/main/src/lmql/ui/playground/src/State.js#L60

**Comment by ggbetz** [comment]
Excellent, Luca, that works like a charm. Thanks!

Will see whether we've some resources to add more options.
