### ISSUE TITLE
Observation - Inference speed decreasing with length of prompt

### ISSUE THREAD

**Issue by SlistInc** [eth-sri/lmql#188]
I just wanted to leave a comment, I don't know if this is known, expected or indeed unavoidable. I noticed that inference starts quite rapidly but the speed decreases signifcantly throughout the prompt / script. It gets to a crawling speed.

Here is my script:

```
argmax(chunksize=64)
    question = "How to successfully grow lemons in Switzerland?"
    "Q: {question}\n\n"
    "Three good people to answer this question would be:\n"
    "1) a[EXPERT_1] Let's call this expert Anton\n"
    "2) a[EXPERT_2] Let's call this expert Bret\n"
    "3) a[EXPERT_3] Let's call this expert Corgo\n"
    "They are all in a confy room and debate how to best answer the question '{question}'.\nThis is how their discussion looks like:\n"
    "- Corgo: 'So, what aspects have to be covered when answering the question?'\n"
    for i in range(5):
        "- [NAME]: '[COMMENT]'\n"
    "After this discussion, Anton proposes an answer to the question '{question}': [ANSWER]"
    "To that they debate improvements to the proposed answer:\n"
    "- Anton: 'How can we improve my proposed answer?'\n"
    "- [NAME]: 'I think you forgot that [COMMENT]'\n"
    "- [NAME]: 'Good point. And you should also consider that [COMMENT]'\n"
    "- [NAME]: 'Another thing you didn't mention is [COMMENT]'\n"
    "- [NAME]: 'You should definitely also add [COMMENT]'\n"
    "- [NAME]: 'Something most people forget is that [COMMENT]'\n"
    "- [NAME]: 'Also add the following point [COMMENT]'\n"

    "After this discussion, Anton proposes a revised and final answer to the question '{question}': [ANSWER]"

from 
    lmql.model("local:llama.cpp:/LOCAL_PATH/orca_mini_v3_7b.ggmlv3.q5_K_M.bin", n_ctx=4000) 
where
    STOPS_AT(EXPERT_1, ".") and 
    STOPS_AT(EXPERT_1, ",") and 
    STOPS_AT(EXPERT_1, "\n") and
    STOPS_AT(EXPERT_2, ".") and 
    STOPS_AT(EXPERT_2, ",") and 
    STOPS_AT(EXPERT_2, "\n") and
    STOPS_AT(EXPERT_3, ".") and 
    STOPS_AT(EXPERT_3, ",") and 
    STOPS_AT(EXPERT_3, "\n") and
    STOPS_AT(COMMENT, "\n") and
    STOPS_AT(COMMENT, ".") and 
    NAME in set(["Anton", "Bret", "Corgo"]) 
```

What I observe with this script / prompt:
- Very quick inference of the first experts (within a minute)
- After two hours I got to:
```
 Q: How to successfully grow lemons in Switzerland?⏎
⏎
Three good people to answer this question would be:⏎
1) a Swiss farmer who grows lemons commercially, Let's call this expert Anton⏎
2) a hobbyist gardener who has grown lemons successfully in Switzerland, Let's call this expert Bret⏎
3) a botanist or plant scientist with experience growing citrus fruits in Europe, Let's call this expert Corgo⏎
They are all in a confy room and debate how to best answer the question 'How to successfully grow lemons in Switzerland?'.⏎
This is how their discussion looks like:⏎
- Corgo: 'So, what aspects have to be covered when answering the question?'⏎
- Anton: 'Well, we need to consider climate, soil conditions, and planting techniques.'⏎
- Bret: 'And of course, choosing the right variety for Switzerland.'⏎
- Corgo: 'Indeed, lemons are not native to Europe, so it is essential to select a cultivar that can thrive in the local climate.'⏎
- Anton: 'That's true.'⏎
- Bret: 'I would also mention proper pruning and fertilization.'⏎
After this discussion, Anton proposes an answer to the question 'How to successfully grow lemons in Switzerland?': 
```
- I see these statistics
```
Tokens: 792, Req.: 32, Avb: 0
Time: 8450.9s, 2.96 tok/step
```
- I observe that the response from the LLM seems to come in quite quickly, but the start of getting the response for a field takes more and more time.

What I tried:
- different chunk sizes
- local:llama.cpp and llama.cpp via lmql serve-model

My setup:
- M2 Macbook pro 16 Gb RAM (hence the 7b model - it generally works quite fast in llama.cpp)

Please close this issue if it is not an issue per se. I wanted to report it. Of course I would welcome any tips from anyone in a similar situation. I really like LMQL but it's a shame if it slows down so much during execution.

**Comment by lbeurerkellner** [comment]
Thanks for reporting this. Did you run all tests in the playground? Can you try running the same query from within a python scripts. With long sequence length, the playground bottlenecks on the sheer amount of debug information that has to be send and visualised (especially the decoding tree can be become very big).

**Comment by lbeurerkellner** [comment]
For reference with the query code above and `llama-2-7b-chat.ggmlv3.q4_0.bin` for me the program runs in:

~43s for chunksize=4
~66s for chunksize=64

Without GPU off-loading and n_ctx 400 + running without playground via `lmql run file.lmql`, I get:

~1:53m for chunksize=4
~3:03m for chunksize=64

In general I thus think the key factor here is a lower chunksize of ~4 and not running in the playground, when output is expected to be long.

**Comment by SlistInc** [comment]
Thanks a lot for your thorough replies (on a Sunday evening no less!). They helped me in discovering the cause and I made some interesting observations:
- Running with chunksize=4 and without playground did not make a material difference -> it was still slowing down and finally extremely slow.
- I then tried with llama-2-7b-chat.ggmlv3.q4_0.bin (as you did) and it was very fast

-> My initial conclusion was that it was the q5_K_M quantisation
- To confirm I switched back to my model orca_mini_v3_7b.ggmlv3.q5_K_M.bin expecting crawling slow speeds
- It was comparatively fast now! I am super confused.
- Even a 13b model was "acceptably" fast.

-> My final conclusion: I have no idea... switching around models did "something" behind the scenes?

Anyhow, feel free to close this issue. If I can pinpoint the reason I will report again. lmql switched from unusable to usable by just flipping models back and forth - I didn't do any update / upgrade / reboot / change.

**Comment by lbeurerkellner** [comment]
Indeed, that is quite unexpected. I later ran with the orca model as well, but could not find any substantial difference compared to llama-2-7b. Yes, please feel free to report back if things get slow again. The exponential slow down sounds a bit like a caching issue with the llama.cpp backend maybe, so switching models may have cleaned up some bad state. Anyway, let me know if something comes up in the future.
