### ISSUE TITLE
The RUN button in playground was greyed

### ISSUE THREAD

**Issue by PhilipNZ** [eth-sri/lmql#191]
Hi there,

Thank you very much for the fantastic tool! I found this tool several days ago and couldn't wait giving it a go. I have installed a local copy in my computer and played  with the examples provided in the documentation. I can run examples with a (local) Llama2 model from the command line using lmql and/or python. I have really enjoyed it.

But when I tried to launch 

>>lmql playground

I got some issues with the GUI: I can edit the model menu, but the Run button was always grayed and no response to click.

![image](https://github.com/eth-sri/lmql/assets/8109260/859f6e9f-850c-4cc5-82dc-fee6f063b0f3)

Do you have any ideas or any hints on how to fix that? 

I was running it within a docker container with Ubuntu22.04/python3.11/Node.js18.17.1/cuda11.8/lmql0.999999.

Thanks advance!

**Comment by lbeurerkellner** [comment]
Hi there, thanks for reporting. Can you confirm that both ports 3000 and 3004 are exposed by the container and not otherwise taken by your host system.

Another interesting piece of information would be to know if your developer tools in your browser show an error or failed network request. It looks like the playground UI can be served but the actual execution endpoint via 3004 is not reachable.

**Comment by PhilipNZ** [comment]
Hi Luca,

Thanks a lot for your prompt response!

I use the host network as the docker network and this is how I launched the docker container:

>>docker run --env TRANSFORMERS_CACHE=/home/.cache/huggingface/transformers \
    --network host \
    -it --entrypoint /bin/bash --privileged --shm-size 50G \
    --interactive --name lmql-server --rm --gpus '"device=1"'  \
    --volume $(pwd):/home efe78dd73a04


After logging into the docker container, this is how I started the model server:

root@h7:/# CUDA_VISIBLE_DEVICES=1 lmql serve-model NousResearch/Nous-Hermes-Llama2-13b --cuda 

and this is what I got:
[Serving LMTP endpoint on ws://localhost:8080/]
[Loading NousResearch/Nous-Hermes-Llama2-13b with AutoModelForCausalLM.from_pretrained(NousResearch/Nous-Hermes-Llama2-13b, 'device_map': 'auto')]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:29<00:00,  9.71s/it]
[NousResearch/Nous-Hermes-Llama2-13b ready on device cuda:0]

Then I launched another docker container with the same command as the server container (using different container name), and within the new docker container, I ran

root@h7:/# lmql playground

The terminal flashed through the following
"""
[lmql playground /usr/local/lib/python3.11/dist-packages, liveserver=localhost:3004, ui=localhost:3000]
1.22.19
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.15s.
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.63s.
yarn run v1.22.19
$ /usr/local/lib/python3.11/dist-packages/lmql/ui/playground/node_modules/.bin/cross-env yarn run start
yarn run v1.22.19
$ /usr/local/lib/python3.11/dist-packages/lmql/ui/live/node_modules/.bin/cross-env node live.js
$ react-scripts start
livelib server listening on http://localhost:3004/
"""

and stopped at
![image](https://github.com/eth-sri/lmql/assets/8109260/95fab688-f943-4561-9610-a161c9d4b94d)

It looked all good to me, but when I tried to access it, I got stuck with the grayed Run button:
![image](https://github.com/eth-sri/lmql/assets/8109260/9bca859b-cfc3-4736-808f-1a08bfd20ec3)


What else I have tried:

1. Running 
root@h7:/# lmql playground
within the server docker container, but the outcome was the same.

2. Launching the docker container with 

>>docker run --env TRANSFORMERS_CACHE=/home/.cache/huggingface/transformers \
    -p 3000:3000 -p 3004:3004 -p 8080:8080 ............

but it didn't work either.

**Comment by PhilipNZ** [comment]
Update:

I launched the playground with

>> lmql playground --live-port 3001 --ui-port 3000

And it works!!

Looks like something wrong with port 3004 although I don't know exactly what it is.

**Comment by lbeurerkellner** [comment]
Great that it works now :) Did you check if anything was running on 3004 in the other setup? Maybe launching two containers was an issue?

**Comment by PhilipNZ** [comment]
Yes. It was in use by some other process and I failed to notice that. It doesn't really matter whether I launch the playground within the server container or a separate one as long as they share the network. 

Thanks a lot for the package! I really enjoy it!
