### ISSUE TITLE
Negative contstraints

### ISSUE THREAD

**Issue by morfeusys** [eth-sri/lmql#193]
I'm not sure this feature is possible or exists for now, but it would be very helpful to have a negative constraints like
`VAR not in set(["1", "2", "3"])` to filter all unnecessary values.

Thank you!

**Comment by lbeurerkellner** [comment]
Hi there. Indeed, there already is some support for this, for instance you can write:

```
"Say 'this is a test':[RESPONSE]" where not "test" in RESPONSE and not "is" in RESPONSE
```

Although I admit this is not a very good syntax if you have many things to include. We are also working on regex support for this, but it is not quite there yet. Hopefully soon :)

**Comment by morfeusys** [comment]
@lbeurerkellner thank you for your response! I will try this.
