### ISSUE TITLE
Python nested queries can't be methods

### ISSUE THREAD

**Issue by wmiller** [eth-sri/lmql#197]
Nested queries in Python don't seem to work when they are methods of a class. This code asserts inside compiler.py:
```
class Question:
    def __init__(self):
        self.model = lmql.model(Config.model_path, n_ctx=Config.model_context_size)

    @lmql.query
    def chain_of_thought(self):
        '''lmql
        """A. Let's think step by step.
        [@debug_print REASONING]
        Therefore the answer is[ANSWER]""" where STOPS_AT(ANSWER, ".")
        return ANSWER.strip() 
        '''

    @lmql.query
    def question(self):
        '''lmql
        argmax
            """Q: Why is the sky blue?
            [ANSWER: self.chain_of_thought]"""
            return ANSWER.strip()
        from
            self.model
        '''
```
This is the error:
`...\.venv\Lib\site-packages\lmql\language\compiler.py", line 447, in transform_TypeExpr
    assert False, "compiler: invalid type expression: '{}'".format(node)`

**Comment by lbeurerkellner** [comment]
Thanks for reporting this. I just had a look, and there is some deeper reason this is not enabled yet, but I am looking into it. I had not thought of this case before. As a workaround I suggest factoring out the nested query as a top-level function and passing self as an explicit parameter, if you need to use it in the nested query code.

**Comment by wmiller** [comment]
Yep, that works fine. Interestingly, I tried making the methods static, and that didn’t work either. Same error.

**Comment by lbeurerkellner** [comment]
I just added support for nested query methods on 'main'. `@staticmethod` should also be supported now.

**Comment by wmiller** [comment]
Awesome! Thank you!
