### ISSUE TITLE
Why is LMQL a lot more costly (3-10x more requests) compared to just a simple prompt

### ISSUE THREAD

**Issue by banacer** [eth-sri/lmql#199]
Consider the following example:
- We have a restaurant review, and we want to write a sentiment analysis prompt that provide the LLM with a guideline for scoring and asks for justification. I write the code as follows:
```
@lmql.query
def scoring():
    '''lmql
    """
    Provide 2 sentences to provide justification for the score:
    - [EVIDENCE1]
    - [EVIDENCE2]
    output integer score only: [SCORE]""" where STOPS_AT(EVIDENCE1, ".") and STOPS_AT(EVIDENCE2, ".")
    return {
            "evidence": [EVIDENCE1, EVIDENCE2],
            "score": SCORE.strip()
        }
    '''

def review_scoring_guideline():
    return """The scoring guideline for restaurant reviews is the following:
        1: Very poor experience. The food, service, and ambiance were all below expectations.
        2: Below average experience. Some aspects of the restaurant were satisfactory, but overall it did not meet expectations.
        3: Average experience. The restaurant met expectations but did not exceed them. The food, service, and ambiance were all satisfactory.
        4: Above average experience. The restaurant exceeded expectations in some areas. The food, service, or ambiance were particularly good.
        5: Excellent experience. The restaurant exceeded expectations in all areas. The food, service, and ambiance were all outstanding.
        After each review, I will ask you to SCORE the review. To do so, evaluate the review against the guideline by outputing a score as an integer from 1 to 5.
        """
@lmql.query(model="openai/gpt-3.5-turbo-0613")
async def evaluate_tweet(tweet):
    '''lmql
    argmax(chatty_openai=True, cache=True)
    """
    You goal is to score the following restaurant review:
    tweet: {tweet}
    {review_scoring_guideline()}
    [SCORE: scoring]"""
    return {
        "score": SCORE,
    }
    '''

async def main():
    tweet = """Ate here a few months back for Restaurant Week. Overall was a decent experience but not sure I would go back. Details included below:
Food: we started with the garlic shrimp which were the best thing we ate - plump, juicy, and flavorful with crusty bread to soak up the garlic sauce. We followed with the branzino, which was cooked well, but the whole dish lacked a bit of flavor. We ended with the Thai bread pudding which was not our favorite dessert, the cream wasn't great and the dish had an odd flavor.
Drinks: we had a fruity cocktail with Mezcal I believe but did not really enjoy it
Ambience: nice interior, we were in the upper section
Service: decent waiting service but they accidentally kept my credit card after the transaction... thankfully the waiter noticed once I started to look around for it as we were leaving.
    """
    x = (await evaluate_tweet(tweet))[0]
    print(x)
    print(get_stats())
    

# Call the main function
asyncio.run(main())
```

When I inspect the requests content, it's sending the same prompt over and over again resulting in 2000 tokens sent for this simple example. 
If I concat everything into one prompt by providing clear instruction it costs ~600 tokens. 
Am I doing anything wrong or it this how LMQL works. Programmability is worth it but the cost is inefficient especially if you have thousands of reviews.
This is dummed down example of my actual usecase but when I send my usecase, it ends up sending 15000 tokens when I do it for 1500 tokens.

Any thoughts on how one can make LMQL more efficient when writing it?

**Comment by banacer** [comment]
closing as I found a similar issue https://github.com/eth-sri/lmql/issues/131

**Comment by lbeurerkellner** [comment]
Hi there :) Did #131 help you in reducing costs in any way? You may be interested in the openai_chunksize parameter as documented here https://docs.lmql.ai/en/stable/language/openai.html#configuring-speculative-openai-api-use.

Playing around with this depending on query behavior can also help reduce cost significantly, especially if speculative execution works well.

**Comment by banacer** [comment]
Yes it did. In my real case. I'm now down to ~4000 tokens. by simply refactoring the prompt further and removing the "-" as each one ends up sending a new request. I'm definitely looking forward to open source taking over gpt-4 and have easy access to newer models like LLama2 as openAI api is very limited and can't leverage the more complex constraints in LMQL
