### ISSUE TITLE
Support custom OpenAI-compatible endpoints like VLLM

### ISSUE THREAD

**Issue by bitnom** [eth-sri/lmql#204]
Is it currently possible to set a custom openai endpoint? https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#openai-compatible-server

If not, it would be a good thing.

**Comment by bitnom** [comment]
Looks like this will have to happen first: https://github.com/vllm-project/vllm/issues/379

**Comment by lbeurerkellner** [comment]
Yes, please refer to #143 to track vLLM support in the future. As said there, we are definitely willing to add support but are still waiting out their integration of logit biasing.
