### ISSUE TITLE
[Question]: How To Retrive Multiple Responses For The Same Variable?

### ISSUE THREAD

**Issue by rsomani95** [eth-sri/lmql#212]
I setup a system prompt in the playground that conforms to the exact format I want, which is a list of `N` single line titles (called "[PROMPT]" in the lqml query. However, when I try to use this inside the Python runtime, I'm only able to retrieve the last generated title.

```python
@lmql.query
async def generate_prompts(
    prompt: str,
    num_responses: int = 4,
):
    '''lmql
argmax
   """
   Imagine you are a dull, boring bureaucrat that's been writing government memos all your life.
   I'd like you to give me creatively dull titles for the following prompt: {prompt}

   TITLE LIST:

   """

   for i in range(num_responses):
      "- [PROMPT]"

from
   'openai/gpt-3.5-turbo'
where
   STOPS_AT(PROMPT, "\n")
    '''
```

This is how I've been calling the function in a Jupyter environment:

```python
results = await generate_prompts(prompt="The US government has decided to break up tech monopolies")
result = results[0]
```

which gives me the following output:
<img width="822" alt="CleanShot 2023-09-20 at 11 42 54@2x" src="https://github.com/eth-sri/lmql/assets/17111474/9fbed7ca-0305-4d9b-b56e-5410a6a329e9">

I'd expect to retrieve all generated instances of the `["PROMPT"]` variable here. However, only the last generated response is retained. 

---

I'm not sure how to best achieve this and would appreciate any guidance you can provide.
Thanks!

**Comment by lbeurerkellner** [comment]
Hi there. To better understand what is happening here, you have to consider the semantics of template variable in LMQL. In your core loop you have:

```python
for i in range(num_responses):
    "- [PROMPT]"
```

Now, in pseudo-code what happens during execution is the following:

```python
prompt = "<prompt so far>"
for i in range(num_response):
   prompt += "-"
   PROMPT = llm.generate(prompt)
print("PROMPT is", PROMP)
```

In your loop the prompt is continuously extended by the new response and then the local variable `PROMPT` is assigned the last generated title value. Across multiple iterations of your loop, however, this also means that the value of `PROMPT` will be overwritten again and again, until the loop terminates. Only the last assignment will be maintained, and thus be contained in the final result.

**Solution:** The pattern to solve this is in standard Python and also in LMQL is the following:

```python
titles = []

for i in range(num_responses):
    "- [PROMPT]" where STOPS_AT(PROMPT, "\n")
    titles += [PROMPT]

return titles
``` 

We create a new `titles` list and on each newly generated title, we append the most recent result. Once the loop terminates, we return `titles` as the overall result of our query. 

When running this adjusted LMQL program from Python, the return value of your query will no longer be LMQLResult objects, but rather the custom list of `titles` as returned by your program. This way, you can get a list of all generated titles. I hope this clarifies your question.

**Comment by rsomani95** [comment]
@lbeurerkellner that's excellent. your explanation makes a lot of sense, and solves the problem above.

**Comment by lbeurerkellner** [comment]
Always happy to help. Closing this then.
