### ISSUE TITLE
Can't find info where I can receive debug information about  distribution and params (n, topk, temperature)

### ISSUE THREAD

**Issue by anagaykinnewo** [eth-sri/lmql#214]

**Comment by lbeurerkellner** [comment]
As far as I understand the issue description there may be several feature in the recently released 0.7 that address this:

1. LMLQ now support more inference parameters, including top_k, top_p and different forms of penalties: https://github.com/eth-sri/lmql/issues/227 
2. We now support [Inference Certificates](https://lmql.ai/docs/lib/inference-certificates.html), which allow you to inspect the exact calls that are made to the underlying LLMs, including inference parameters and the concrete tokenised prompts. Certificates also include calls that are made to compute distributions.

I will close this issue based on this. Please re-open/respond with more information if this does not cover your request.
