### ISSUE TITLE
Error while running in colab, while working fine in the playground.

### ISSUE THREAD

**Issue by mohamedsobhi777** [eth-sri/lmql#225]
The query works fine giving reasonable responses in the playground while exceeding the maximum tokens in colab, specifying a maximum number of tokens results in a very long number as a response (reaching the number of tokens i specified).

----
Query (in playground):
`
sample(temperature=1)
    "The following are your records for the total calories consumed and burned yesterday (calories burned is less than calories consumed)."

    "Calories Consumed:[CALORIES_CONSUMED]."
    "Calories Burned:[CALORIES_BURNED]."
from 
    "openai/text-davinci-003" 
where
    INT(CALORIES_CONSUMED) 
    and INT(CALORIES_BURNED)
`

------------------------------------------

Code (in Colab):
@lmql.query()
async def query():
    '''
sample(temperature=1)
    "The following are your records for the total calories consumed and burned yesterday (calories burned is less than calories consumed)."

    "Calories Consumed:[CALORIES_CONSUMED]."
    "Calories Burned:[CALORIES_BURNED]."

from 
    "openai/text-davinci-003" 
where 
    INT(CALORIES_CONSUMED) 
    and INT(CALORIES_BURNED)
    '''
out = await query()

print(out[0].variables)

Error:
<img width="1650" alt="Screenshot 2023-10-03 at 16 29 05" src="https://github.com/eth-sri/lmql/assets/33491613/df501d0b-6a8f-4387-9b7e-88ad7d793148">

**Comment by lbeurerkellner** [comment]
Thanks for reporting. Can you check/report the LMQL version used on Colab? The Playground is always the latest `main`, so there may be a difference.

**Comment by mohamedsobhi777** [comment]
It's the latest stable version '0.0.6.6', i'm not sure if the playground is running v0.7b3 or 0.0.6.6.

**Comment by lbeurerkellner** [comment]
The playground always uses the latest 'main', so I would assume that [installing the latest dev version](https://github.com/eth-sri/lmql#installing-the-latest-development-version) in Colab should fix the issue.
