### ISSUE TITLE
additional decoding options?

### ISSUE THREAD

**Issue by ambroser53** [eth-sri/lmql#227]
Is there a way to specify additional parameters to the decoders outside of just temperature and number of beams? Parameters such as top_k, top_p and repetition_penalty that are all available through the regular HF generate functions?

**Comment by lbeurerkellner** [comment]
Currently, there is not, but we plan to add this very soon. It is just a matter of piping through the relevant parameters to OpenAI, llama.cpp or Transformers respectively, as we use standard generate() function for all of them, which typically support these kinds of sampling parameters.

**Comment by lbeurerkellner** [comment]
I just pushed support for additional parameters to "main". This includes `top_k`, `top_p`, `repetition_penalty`, `frequency_penalty` and `presence_penalty` for OpenAI, llama.cpp and Transformers where applicable. 

Let me know if there are any other specific parameters that you would like to see supported.
