### ISSUE TITLE
Lmql for output parsing with llamaindex and langchain 

### ISSUE THREAD

**Issue by smyja** [eth-sri/lmql#237]
It would be nice to be able to use lmql with llamaindex or langchain for outputparsing especially for llama models like 70b. llamaindex and langchain have hundreds of data loaders and llms also.

**Comment by smyja** [comment]
> It would be nice to be able to use lmql with llamaindex or langchain for outputparsing especially for llama models like 70b. llamaindex and langchain have hundreds of data loaders and llms also.

its availaible already, doc search doesn't work though.

**Comment by lbeurerkellner** [comment]
Hi there, yes LC and LI are both supported. Doc search is titles-only for now, but we are investigating how to enable an improved full-text one :)
