### ISSUE TITLE
`return None` is ignored

### ISSUE THREAD

**Issue by davidpomerenke** [eth-sri/lmql#243]
```python
import lmql

@lmql.query
def label():
    '''lmql
    "Hi, [COMPLETION]."
    return None
    return "Something"
    '''

print(label())
```

Actual output: `Something`
Expected output: `None`
Workaround: Use a different return value such as `False`, which is not ignored.
Version: LMQL 0.7.3

Thank you for this great library! ❤️

**Comment by lbeurerkellner** [comment]
Thanks for reporting and the nice words :)

Just fixed the issue and pushed it to `main`. `return None` should now be properly supported. This also includes just `return`.

* `return None` will return the value `None`
* Just `return` will return with an `lmql.LMQLResult`

**Comment by davidpomerenke** [comment]
That's a very nice solution, thank you!
