### ISSUE TITLE
Language Model Query Language (LMQL) Syntax Highlighting 0.0.3

### ISSUE THREAD

**Issue by TomExMachina** [eth-sri/lmql#245]
Version 0.0.1 is what's currently in the vscode marketplace and here in the main branch. Here's what it looks like:

![Selection_143](https://github.com/eth-sri/lmql/assets/139252310/f73a1845-c5d2-4370-85d6-bb6bdaf20a10)

I wanted features 0.0.1 didn't have, and started working toward them (0.0.2, which I'm about to submit a PR for):

![Selection_144](https://github.com/eth-sri/lmql/assets/139252310/8d60b18a-df1e-4db8-8f7c-7afc2c743e17)

It's better but still not great. Let's take a look at how it could be better  - v0.3 (Big Sexy)

![Selection_141](https://github.com/eth-sri/lmql/assets/139252310/73fe78db-25f1-4234-87c6-2fee6b6fde0a)

**Comment by TomExMachina** [comment]
Also, maybe we could define what a version 0.1.0 or even 1.0.0 is supposed to look like.

**Comment by viktor-ferenczi** [comment]
Do we have syntax highlighting for JetBrains PyCharm?

**Comment by TomExMachina** [comment]
> Do we have syntax highlighting for JetBrains PyCharm?

I don't think so. Aren't those made in Java? It's never seemed like a fun endeavor, so I've never touched Java. PyCharm is great though.

**Comment by lbeurerkellner** [comment]
Awesome work, this just got merged via #246. Thanks again.
