### ISSUE TITLE
Problem with distribution when used with no other generation

### ISSUE THREAD

**Issue by BedirT** [eth-sri/lmql#247]
Hey,

I am having an issue using the `distribution` clause when I try to use it with no other generation context.

Here is a simple example:
```python
argmax
    "Select something"
    "Choice: [CLS]"
distribution
    CLS in [" positive", " neutral", " negative"]
```
This throws me an error:
```bash
File "/home/pyodide/lmql/runtime/context.py", line 29, in get_tokenizer
    assert len(_context.get()) > 0, "No tokenizer set in this context"
AssertionError: No tokenizer set in this context
App exited with status 1
```
If I instead use a generation with the same context, it works well though:
```python
argmax
    "Select something [A]"
    "Choice: [CLS]"
distribution
    CLS in [" positive", " neutral", " negative"]
```
Am I missing something? (Also the documentation around distribution is very scarce)

**Comment by lbeurerkellner** [comment]
Thanks, this was a bug. I just pushed a fix to `main`.

If you are interested in queries that just do a scoring operation via `distribution`, you may (as a workaround but also generally), be interested in the *Generations API* as introduced with LMQL 0.7. 

It allows you to easily express this kind of scoring:

```python
import lmql

m = lmql.model("openai/text-davinci-003")

r = m.score_sync("Hello", ["You", "World"])
print(r)
# lmql.ScoringResult(model='openai/text-davinci-003')
# -'You': -10.360345840454102
# -'World': -3.5903143882751465
print(r.probs())
# [0.00114635 0.99885365]
```

You can learn more about it in the [corresponding documentation chapter](https://lmql.ai/docs/lib/generations.html).
