### ISSUE TITLE
Playground with Azure API

### ISSUE THREAD

**Issue by steve36871** [eth-sri/lmql#248]
Hello! I just started with LMQL and would like to use it with the Azure API, since my company uses this cloud platform.
I found a [page on configuring Azure](https://lmql.ai/docs/models/azure.html), but it seems not to handle the deployment name in the environment variables. Any tips on configuring the playground using Azure?

**Comment by lbeurerkellner** [comment]
Hi there, are you using the browser-based playground at lmql.ai/playground, or the playground of a local install via `lmql playground`?

To configure Azure access w/o environment variables, check out the second part of the linked documentation chapter: https://lmql.ai/docs/models/azure.html#configuration-via-lmql-model. 

An `lmql.model(...)` object can be passed in the [`from` clause of a query](https://lmql.ai/docs/models/#option-b-queries-with-from-clause). When running from within Python you can also pass it as `model=lmql.model(...)` to e.g. the `@lmql.query` decorator.

**Comment by steve36871** [comment]
Hello Luca,
Thank you very much for getting back to me.
I tried to supply the following query now:

```
"Say 'this is a test':[RESPONSE]" where len(TOKENS(RESPONSE)) < 10
from "openai/<deployment_name>"
```

I launched it as follows:
`OPENAI_API_TYPE=azure OPENAI_API_BASE="<base_url>" OPENAI_API_KEY=<api_key> lmql playground`

However, I get these errors:
```
...
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/mdsas_gpt_4/resolve/main/tokenizer_config.json
...
   raise TokenizerNotAvailableError("Failed to locate a suitable tokenizer implementation for '{}' (Make sure your current environment provides a tokenizer backend like 'transformers', 'tiktoken' or 'llama.cpp' for this model)".format(model_identifier))
lmql.runtime.tokenizer.TokenizerNotAvailableError: Failed to locate a suitable tokenizer implementation for 'mdsas_gpt_4' (Make sure your current environment provides a tokenizer backend like 'transformers', 'tiktoken' or 'llama.cpp' for this model)
App finished running with exit code 1
```

I wonder why it is looking at a huggingface URL now. Any ideas?

**Comment by lbeurerkellner** [comment]
It looks like your LMQL cannot derive the tokenizer to use from your deployment name `mdsas_gpt_4`.  Can you try the following instead:

```
from "openai/lmql.model("openai/mdsas_gpt_4", tokenizer="gpt-4")
```

**Comment by steve36871** [comment]
@lbeurerkellner 
Thanks again. It did not work though:

```
"/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tokenize.py", line 525, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (3, 0))
App finished running with exit code 1
```

**Comment by lbeurerkellner** [comment]
This looks like a parsing error, before the query runs. The full snippet I am testing for this in the playground, is the following:

```
import os

os.environ["OPENAI_API_TYPE"] = "azure-chat"
os.environ["OPENAI_API_BASE"] = "<API_BASE>"
os.environ["OPENAI_API_KEY"] = "<API_KEY>"

"Say 'this is a test':[RESPONSE]" where len(TOKENS(RESPONSE)) < 10
from lmql.model("openai/gpt-4", tokenizer="gpt-4")
```

Does this match your query program?

**Comment by steve36871** [comment]
@lbeurerkellner 
I think it almost works now, but I see this:

`The completion operation does not work with the specified model, gpt-4. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993`

This looks like a more fundamental issue, right?

**Comment by lbeurerkellner** [comment]
Did you specify `azure-chat` or just `azure` as API type? Make sure to use `azure-chat`, as `gpt-4` is only available as Chat model, not as Completions model.

**Comment by steve36871** [comment]
Success! Thank you! 🎉

**Comment by steve36871** [comment]
@lbeurerkellner 
Apologies, still one more question. I encountered this message on some queries: "Chat API models do not support advanced constraining of the output, please use no or less complicated constraints."

I am especially interested in classification probability (distribution of probability of next tokens). Do you know which Azure model might work for this?

**Comment by steve36871** [comment]
Great! Thank you very much for your answers and the awesome query language. I am excited to put LMQL to good use! 😄
