### ISSUE TITLE
lmtp_client not starting

### ISSUE THREAD

**Issue by motaatmo** [eth-sri/lmql#259]
I'm trying to start the lmtp_client.py script as shown in the documentation with

python src/lmql/models/lmtp/lmtp_client.py

However, I get an error message:

from .errors import LMTPStreamError
ImportError: attempted relative import with no known parent package

Is there something I missed when installing the package?
Greetings!

**Comment by lbeurerkellner** [comment]
Hi there, running `lmtp_client.py` directly is only useful for debugging purposes. What are your trying to achieve? Are you look to just [serve a model(https://lmql.ai/docs/models/hf.html), or are you really trying to use LMTP separately from LMQL?

**Comment by motaatmo** [comment]
Hi, I'm just trying to verify my installation using the client. It seemed
to be the most simple way.

Luca Beurer-Kellner ***@***.***> schrieb am So., 29. Okt.
2023, 11:42:

**Comment by lbeurerkellner** [comment]
I just pushed a fix for the relative import issue in https://github.com/eth-sri/lmql/commit/797a95df085647866ba689d4c88c191d76b2b6d9. Thanks again for reporting this.
