### ISSUE TITLE
The issue of the postprocess_order for STOPS_AT operators.

### ISSUE THREAD

**Issue by zhangyuhanjc** [eth-sri/lmql#269]
## Question
When I use multiple STOPS_AT / STOPS_BEFORE constraints in a single 'where' statement, I found that one of the constraints may does not take effect. 
You can use the following code with the Llama-2-7b-hf model to reproduce this scenario.
```python
@lmql.query
def test():
    '''lmql
    """{{"first_name": "Bruno", "last_name": "Mars", "birthday": "1985-10-0", "age": 32, "hobby": [["sing", "dance"]], "address": {{"street_address": "12345", "city": "New York", "state": "NY", "country":"US"""
    '", "children_name":[["[GEN_STR]"]]' where len(TOKENS(GEN_STR)) < 20 and STOPS_BEFORE(GEN_STR, ']')  and STOPS_BEFORE(GEN_STR, ',') and STOPS_BEFORE(GEN_STR, '"') 
    '''


print(test(model = model))
LMQLResult(prompt='{"first_name": "Bruno", "last_name": "Mars", "birthday": "1985-10-0", "age": 32, "hobby": ["sing", "dance"], "address": {"street_address": "12345", "city": "New York", "state": "NY", "country":"US", "children_name":["John""]', variables={'GEN_STR': 'John"'}, distribution_variable=None, distribution_values=None)
```
As you can see we have STOPS_BEFORE(GEN_STR,'"'),but we got variables={'GEN_STR': 'John"'}
## Log
For the above case, I found in the log (picture below) that the program processes the STOP operator in the following order
1. ]
2. "
3. ,

It seems that the result of STOPS_BEFORE(GEN_STR, ',') overrides the result of STOPS_BEFORE(GEN_STR, '"').

![image](https://github.com/eth-sri/lmql/assets/24644344/3d61b6d5-2c59-496f-b64b-ae8f2dd77040)

## my understanding of this issue
I understand that LMQL orders the STOP operators through postprocess_order. If the stopping_phrase can match an index closer to the beginning, then the STOP statement should be executed later.If my understanding above is incorrect, please correct me.

For the source code in the red box in the figure, I understand that if matched_phrase_index is less than other_matched_phrase_index, then the current stopping_phrase should be processed later to avoid being overwritten by the results of other stopping_phrases. Therefore, would it be more reasonable to change the comparison operator to a greater than sign?

[lmql](https://github.com/eth-sri/lmql/tree/main)/[src](https://github.com/eth-sri/lmql/tree/main/src)/[lmql](https://github.com/eth-sri/lmql/tree/main/src/lmql)/[ops](https://github.com/eth-sri/lmql/tree/main/src/lmql/ops)/ops.py
![image](https://github.com/eth-sri/lmql/assets/24644344/f95dacde-9f24-44f4-8950-b35409ba7bc1)

**Comment by lbeurerkellner** [comment]
Wow, thank you so much for this very detailed ticket, you've got a great eye and understanding of the code base. I finally found the time to have a closer look myself and you are indeed correct about switching the operator. I just pushed a corresponding fix + unit test in https://github.com/eth-sri/lmql/commit/139b5e6d55dd4dff8e26d640219d2c0a68f65e6e. 

Again, thanks a lot :)
