### ISSUE TITLE
Parsing Error for Example Code

### ISSUE THREAD

**Issue by hiiroo** [eth-sri/lmql#285]
Hello everyone, thanks for the amazing tool. I have an issue when I try to run the example given in the following link.

https://lmql.ai/docs/language/overview.html#dynamically-reacting-to-model-output

I am getting the following error. (I believe it is the commit number of the version 9a59739d980a88e64687689b7cecee6cbaf79b78 (From the right top corner))

```
RuntimeError: parsing error: Failed to parse where clause of the query (unexpected indent):

	   STOPS_AT(FURTHER_ANALYSIS, ".") \
```

**Comment by lbeurerkellner** [comment]
Hi hiroo, can you share more information about your setup? Are you running in the Playground or from within Python? 

From the error message it looks like when copying, the indentation of the code may have gotten misaligned. Note that LMQL has the same indentation rules that Python does.

**Comment by hiiroo** [comment]
I just tried again and yes, it was the indentation problem. Sorry for alarming up. Closing the issue.
