### ISSUE TITLE
Model as a parameter

### ISSUE THREAD

**Issue by jvamvas** [eth-sri/lmql#29]
I saw that Python variables are now supported in the "where" clause – that's great news, thank you! :slightly_smiling_face: 

It would also be nice if variables were supported in the "from" clause:

```python
@lmql.query
async def hello(model: str, length: int):
    """
    argmax
        "Hello[WHO]"
    from
        model
    where
        len(WHO) < length
    """

asyncio.run(hello(
    "openai/text-ada-001",
    10,
))
```

However, I would even prefer the following syntax:

```python
@lmql.query("openai/text-ada-001")
async def hello(length: int):
    """
    argmax
        "Hello[WHO]"
    where
        len(WHO) < length
    """
```

**Comment by lbeurerkellner** [comment]
Thanks, this is a good suggestion. I just pushed a fix for (1) to 'main'.

I like the second proposal also. I will definitely look into it and keep this issue as an "enhancement" proposal :)

**Comment by lbeurerkellner** [comment]
With the latest release you can now specify the model as `@lmql.query(model="<MODEL>")` or even when calling a query function via an additional keyword argument.
