### ISSUE TITLE
How does INT constraint work?

### ISSUE THREAD

**Issue by pruksmhc** [eth-sri/lmql#3]
argmax
   "A number: [N]"
from
   'openai/text-ada-001'
where
    INT(N)

If for some reason the token with the highest log probability is not an integer, what would LMQL do?

**Comment by lbeurerkellner** [comment]
LMQL applies logit masking to force the model to predict a sequence of tokens that correspond to an integer value. 

This means, when the model predicts the value of N, during generation we do not allow an arbitrary choice of next token, but limit the set of choices, available to the model, to only those (sub)tokens that correspond to possible integer value. For instance, in the token distribution of the model we would disallow tokens like "four", "hello" and  allow only tokens like "01", "12", "0", etc.. 

This is done automatically by translating the high-level `INT(N)` constraint into a token mask, and masking the output distribution accordingly. To learn more about constraints and how they are implemented, be sure to also read the corresponding chapter in the documentation: https://docs.lmql.ai/en/latest/language/constraints.html

**Comment by pruksmhc** [comment]
As a followup question, with the OpenAI API, it seems like they don't output the distribution (just the top max 5 log probs). What distribution does lmql use then?

**Comment by lbeurerkellner** [comment]
For the OpenAI API there is an additional logit_bias parameter (at least for non-Chat models), which allows you to bias the distribution according to the provided constraints.
