### ISSUE TITLE
Broken Doc Links

### ISSUE THREAD

**Issue by jrinder42** [eth-sri/lmql#302]
There are several broken links in the docs.

**Comment by jrinder42** [comment]
I am making this more general as there are more broken links in the docs. For all intents and purposes, there may be more broken links / anchors that were not caught.

# lmql/docs/docs/language/reference.md

Broken anchors in the `reference.md` file

- [ ] #python-api
- [ ] #legacy-syntax
- [ ] #modern-syntax

# lmql/docs/features/3-models.md

Broken link in the `3-models.md` file

- [ ] ../docs/models/llama.cpp.html

# lmql/docs/docs/models/hf.md

Broken anchor in the `hf.md` file

- [ ] #in-process-model-loading

# lmql/docs/docs/lib/generations.md

Broken anchors in the `generations.md` file

- [ ] #lmql-generate
- [ ] #lmql-score
- [ ] #lmql-set_default_model
- [ ] #llm-score-sync
- [ ] #llm-score
- [ ] #llm-generate_sync
- [ ] #llm-generate

**Comment by jrinder42** [comment]
I noticed that GitHub markdown is not compatible with how the docs are built. Some of the links that are broken in the markdown work on the actual website. 

There is a weird issue that some links (i.e. `#legacy-syntax` in `reference.md`) are changed to the correct anchor when the docs are built. This seems like it is either an issue or odd oversight that luckily works.

**Comment by lbeurerkellner** [comment]
Thanks for raising this. I will look at the different links listed in the PR and fix them.

**Comment by lbeurerkellner** [comment]
I just checked all the links contained in the PR, and made sure they work when viewed from the website (see https://github.com/eth-sri/lmql/commit/a055952b2595fc94ccdc0879830b2954feebb0de). Thanks gain.
