### ISSUE TITLE
Allow specifying model path for hf models

### ISSUE THREAD

**Issue by Ranguna** [eth-sri/lmql#313]
The llama.cpp loader accepts a path for gguf models, but I was not able to find this option for models loaded with hf transfomers. I have quite a few models that I use with https://github.com/oobabooga/text-generation-webui/ and it's not ideal having to download them again just for lmql.

**Comment by lbeurerkellner** [comment]
You should be able to just specify the full (absolute) path as model identifier. Does that work for you?
