### ISSUE TITLE
Is there any way to replicate function calling like in openai assistants api?

### ISSUE THREAD

**Issue by KurtKobalt** [eth-sri/lmql#317]
I'd like to us the LLM to query the user until it has all the parameters required to call an external api. I tried reading the documentation but couldn't find any use case like this. Thanks.

**Comment by lbeurerkellner** [comment]
There is some work happening around bridging to OpenAI function calling. Further, we have shipped preview features around similar functionality with other models (see https://lmql.ai/blog/#lmql-actions-preview for glimps).

All in all, there is no batteries-included solution shipping with LMQL right now. I hope this is helpful.
