### ISSUE TITLE
Client-side (decoding) memory leak with async @lmql.query

### ISSUE THREAD

**Issue by stevenbedrick** [eth-sri/lmql#327]
Hello! I am running into a memory leak with LMQL; it is _not_ related to the GPU, as far as I can tell, and is happening in host memory- i.e., I'm using a separate `lmql serve` process, and that process is working perfectly. The issue is with the python process that is running my LMQL script itself. As I iterate through a dataset, invoking my query once per item, I am seeing a steady monotonic increase in RAM usage, eventually leading to the program running out of memory and crashing. The GPU memory usage is flat, as expected, as is the RAM usage of the `lmql serve` process. 

My program's setup is that I have an async function decorated with `@lmql.query` with my actual LMQL invocation, and then have a wrapper async function that actually invokes lmql. This wrapper function includes some code that  uses a semaphore to coordinate how many simultaneous calls  can be in flight at once (in practice I limit this to the number of GPUs I have available), and and also has some caching logic, but otherwise is basically just calling `await my_lmql_function(....)` and returning the result. The main part of the script iterates over my dataset, and for each item, uses `asyncio.create_task()` to set up a coroutine using the wrapper function. I then have a for loop that runs `asyncio.as_completed()` over the list of coroutines.

In terms of performance, this admittedly-somewhat-convoluted workflow works just fine- the right number of queries are being invoked at the right times, and I see the expected throughput through my dataset. However, memory usage is increasing monotonically- after each time through my loop over `as_completed()`, the memory usage goes up by a few tens of megabytes and doesn't go down. I was worried it was something to do with my caching logic (maybe it was hanging on to a reference to something that had a bigger object graph behind it than I realized), but I've removed that and am seeing the same behavior. I also can confirm that when I restrict the number of concurrent invocations to 1, I see the same behavior. Manually calling `gc.collect()` at the end of the loop doesn't help. While investigating the problem, I also used `objgraph`'s `show_growth()` function and see that there are a lot of new objects being retained after each time through the loop that seem to have their origin in LMQL; as an example:

```
dict                            35598     +2468
list                            20259     +1892
tuple                           36395     +1175
TokenSetConcrete                 2181      +659
FollowMap                        2305      +647
ProgramState                      405      +130
PromptState                       405      +130
TokenMask                         385      +121
DecoderSequence                   303       +81
DeterministicDecoderSequence       80       +41
```

The only thing happening in the body of my loop is that I'm taking the LMQL output, destructuring it a bit, and writing it out to a couple of log files. This does involve creating one or two dictionaries but not thousands.

I am seeing this behavior both on MacOS as well as Linux, and under both Python 3.10 and 3.11. Any advice, thoughts, prayers, etc. would be most welcome!

**Comment by stevenbedrick** [comment]
So after a bunch of work I was able to spot a place in my code where I was running up against a few of asyncio's numerous and abundant foot-guns, and I _think_ I have addressed them. Specifically, I was creating my coroutines all in one go and storing them in a list to iterate over, and so they were hanging around outside of the loop body and thus weren't getting garbage collected. Each one maintained references to surprising amount of LMQL state. I reorganized the code so that I'm making my co-routines a few at a time and am manually clearing them out every so often, and that seems to have mostly done the trick though I am still seeing some weirdness- more investigation under way.

All in all, this has been very educational and I'll probably be able to make a nice tutorial about using LMQL for batch-processing large datasets using the async APIs...

**Comment by lbeurerkellner** [comment]
Hi Steven, thanks for reporting and your investigations around this. Yes, there is quite some state in each query call, so allocating them all at once may not always be good idea. Looking forward to your insights, which should also help us inform future changes to the core, that could make things more lightweights.

Closing this for now, as I don't see an immediately actionable fix here (please feel free to appeal that).

**Comment by stevenbedrick** [comment]
Yeah, no actionable fix or anything other than maybe having some more documentation around best practices on how to use LMQL in an async manner, and about some of the possible "gotchas" hiding in the tall grass. :-)
