### ISSUE TITLE
Step budget exceeded 

### ISSUE THREAD

**Issue by nyacg** [eth-sri/lmql#33]
Even after setting the `max_len` variable I still exceed the step budget. Looking into the code it looks like I need to set the `step_budget` parameter on the `argmax` instead

I'm not sure if [the docs](https://docs.lmql.ai/en/latest/language/decoders.html#other-decoding-parameters) need updating or if the code needs changing.

Here's the error I received:
```
warning: step budget exceeded
... (stack trace)
AssertionError: decoder argmax did not finish with dc.finish(), which means no result sequences were returned. 
The reason for this may be a too small max_len value (max_len=9999999999999999) 
```

Using version `0.0.5.1`

P.S. Really enjoying the LMQL declarative prompting, feels a bit like React vs jQuery (as compared to Langchain)

**Comment by lbeurerkellner** [comment]
Hi there :) Happy to hear that you are enjoying LMQL. Thanks for raising this.

Right, `step_budget` is another parameter that you potentially need to consider. It forms an upper bound to the maximum number of "steps" the underlying decoding algorithms is allowed to take. For argmax this corresponds directly to the sequence length, for others like beam/best_k, it has a slightly different meaning.

To make this a little more convenient, I just pushed a change on 'main' (should be in the next release), such that step_budget is automatically chosen to be at least as high as max_len. So you should not encounter this issue anymore.

**Comment by nyacg** [comment]
Brilliant, thanks!
