### ISSUE TITLE
Further token efficiency on `in` conditions

### ISSUE THREAD

**Issue by CircArgs** [eth-sri/lmql#37]
Thinking about conditions such as `where SOMETHING in ['aaa', 'bbb', 'ccc']` say a model produces a token `a` for `SOMETHING`, can LMQL be made more efficient to infer that the only possibility is then `aaa` and skip to the end of `SOMETHING`?

**Comment by lbeurerkellner** [comment]
Yes it can, and we actually have a first working implementation for this. I just need to finalize the last parts on the HF side. Should be ready soon :)
