### ISSUE TITLE
[Windows non-WSL] playground won't start

### ISSUE THREAD

**Issue by wsligter** [eth-sri/lmql#4]
playground won't start on windows system (all requirements met) with error:
'REACT_APP_BUILD_COMMIT' is not recognized as an internal or external command,
operable program or batch file.
pls advise.

**Comment by lbeurerkellner** [comment]
Hi wsligter, could you provide more details on your setup. Did you install the `pip` package or are you running directly from source?

**Comment by mactronmedia** [comment]
Same here. Windows 10

  lmql playground
[lmql playground C:\Users\mactron\AppData\Local\Programs\Python\Python311\Lib\site-packages, liveserver=localhost:3004, ui=localhost:3000]

> yarn@1.22.19 preinstall C:\Users\mactron\AppData\Roaming\npm\node_modules\yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

C:\Users\mactron\AppData\Roaming\npm\yarn -> C:\Users\mactron\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js
C:\Users\mactron\AppData\Roaming\npm\yarnpkg -> C:\Users\mactron\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js
+ yarn@1.22.19
updated 1 package in 0.334s
yarn install v1.22.19
yarn install v1.22.19
[1/4] Resolving packages...
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.14s.
'PORT' is not recognized as an internal or external command,
operable program or batch file.
success Already up-to-date.
Done in 0.58s.
'REACT_APP_BUILD_COMMIT' is not recognized as an internal or external command,
operable program or batch file..

**Comment by lbeurerkellner** [comment]
I think they underlying issue here is that you are not running LMQL in a WSL environment. For now, this is the only option to use LMQL on Windows. We will investigate how to extend support to general shells. 

The errors suggest, that nothing major is amiss here, but rather that just the environment variables have to be handled differently. Thanks for your understanding.

**Comment by mosheduminer** [comment]
This issue is closed, but I cannot run the playground on windows (using version `0.7b1`). I figure that using [`cross-env`](https://github.com/kentcdodds/cross-env) would be a good fix?

**Comment by lbeurerkellner** [comment]
Are you running with WSL or standard cmd.exe/PowerShell?

**Comment by mosheduminer** [comment]
I am using regular CMD, I would prefer not to use wsl for this.

**Comment by lbeurerkellner** [comment]
A PR would be awesome and very much appreciated :)

**Comment by lbeurerkellner** [comment]
Thanks to @mosheduminer, the current 'main' now allows the playground to be launched from cmd.exe, e.g. via `python -m lmql.cli playground`.
