### ISSUE TITLE
Visibility into LLM requests

### ISSUE THREAD

**Issue by yang** [eth-sri/lmql#40]
Is there already any way to easily see what are the requests to the LLM being made? (Esp. for API based LLMs.) Just having trouble parsing excerpts like this from the docs (e.g. is it actually generating $O(n^2)$ requests where $n$ scales with length?), and what are the logit biases generated for various constraint expressions, etc.:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/7129/233824536-853e92e8-1c70-47b6-9344-f65e9c46f2fb.png">

Apologies if this already exists and I'm just missing it!

**Comment by lbeurerkellner** [comment]
There are a couple of ways to see what is happening internally with API-based models:

* In the playground in the bottom right of the query editor, you can see real-time query statistics, including no. of requests, tokens and estimated cost when using OpenAI models:
   
   <img width="186" alt="image" src="https://user-images.githubusercontent.com/17903049/233836413-7e8ac978-4038-4b8e-a690-7090d8695513.png">


* There is a decoder option ‘chatty_openai=True’ which you can enable, and you will see all OpenAI request payloads printed to the console.

* Lastly, if you want query stats when running in Python, the following snippets prints them:

   ```
   import lmql.runtime.bopenai as bopenai
   print(bopenai.Completion.get_stats())
   ```
