### ISSUE TITLE
LMQL Playground ends in react error

### ISSUE THREAD

**Issue by SimulacraAtTanagra** [eth-sri/lmql#41]
Installed latest version of Python, Node.JS and npm, plus react-scripts. Getting the following:

`C:\WINDOWS\system32>lmql playground
[lmql playground C:\Users\Simulara\AppData\Local\Programs\Python\Python310\lib\site-packages, liveserver=localhost:3004, ui=localhost:3000]

changed 1 package in 848ms
yarn install v1.22.19
yarn install v1.22.19
[1/4] Resolving packages...
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.43s.
'PORT' is not recognized as an internal or external command,
operable program or batch file.
success Already up-to-date.
Done in 1.63s.
'REACT_APP_BUILD_COMMIT' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>`

**Comment by lbeurerkellner** [comment]
Thank you for raising this. We are tracking the issue in https://github.com/eth-sri/lmql/issues/4.

We currently only support running LMQL from within a WSL environment. We are looking into extending support to cmd.exe.
