### ISSUE TITLE
Multiple STOPS_BEFORE constraint issue

### ISSUE THREAD

**Issue by JasperDekoninck** [eth-sri/lmql#49]
The following query results in an error (both in the Python package and the Playground)

```python
sample(temperature=0.8, openai_chunksize=128, max_len=128, chatty_openai=True)
    "The movie review in positive sentiment is: '[OUTPUT]"
FROM
    "openai/text-ada-001"
WHERE
    STOPS_BEFORE(OUTPUT, "\\n") and STOPS_BEFORE(OUTPUT, "n")
```

```AssertionError: The specified set of constraints contains multiple incompatible postprocessing operations for the same variable. The conflicting operations are:  and . Please make sure the used constraints implement postprocess_order for each other, to use them together.```

The same query with "STOPS_AT" instead of "STOPS_BEFORE" works.

**Comment by lbeurerkellner** [comment]
Thanks, this will be fixed in the next release (see commit).
