### ISSUE TITLE
INT type constraint not working with HF

### ISSUE THREAD

**Issue by Ryul0rd** [eth-sri/lmql#68]
```
argmax
    'A number: [N]'
from
    'gpt2-large'
where
    INT(N) and len(N) < 3
```
The above example is copied directly from the documentation except it has been modified to use gpt2-large instead of the OpenAI API and I'm using a length requirement. When I run it, I get the following error: `ValueError: invalid literal for int() with base 10: '  '`. Running this without the length requirement just seems to run forever.

**Comment by lbeurerkellner** [comment]
Thanks for reporting this. This seems to be an issue with the recently introduced post processing semantics, where the value is converted to a Python `int()`.

**Comment by lbeurerkellner** [comment]
This should be fixed on 'main' and will be part of the next release.
