### ISSUE TITLE
Single process to load model locally without serve-model

### ISSUE THREAD

**Issue by praveenv** [eth-sri/lmql#73]
Is there a way to avoid having to separately serve a HF Transformer model using `lmql serve-model` and instead load it locally as part of the python script (similar to traditional HF Transformers examples) ? 

I am currently in a situation where access to ports on our server is limited (permission issues), and would like to load the model locally. 

I see a LocalClient class [here](https://github.com/eth-sri/lmql/blob/main/src/lmql/model/local_client.py) , but am not sure if this would solve my problem / how to go about using it. 

Any help would be appreciated!

**Comment by lbeurerkellner** [comment]
Hi @praveenv, this is indeed possible. Instead of using `lmql serve-model` you can specify e.g. `local:gpt2` as model in your query, which will load the model in the same process, the query is executed in. Then you won't need an additional `serve-model` command.

**Comment by praveenv** [comment]
Perfect! Thank you so much @lbeurerkellner

**Comment by lbeurerkellner** [comment]
Happy to help. There are some performance gains with local models on 'main' already, if the current release version is not fast enough. So feel free to test-drive that as well `pip install git+https://github.com/eth-sri/lmql`. I added a chapter to the docs as well: https://docs.lmql.ai/en/latest/language/hf.html#in-process-model-loading (this refers to the state on 'main').
