### ISSUE TITLE
Allow queries constructed via lmql.run to be directly usable in LangChain

### ISSUE THREAD

**Issue by praveenv** [eth-sri/lmql#76]
The documentation shows an example of using LMQL from LangChain integration using a python function with the `@lmql.query` decorator ([link](https://docs.lmql.ai/en/latest/python/langchain.html#Using-LMQL-from-LangChain))

Is there a way to use an LMQL query string (that can be executed using `lmql.run(query)`) as part of a simple `LLMChain` in LangChain? Any pointers/examples would be appreciated! 

I would like to avoid having to explicitly write an LMQL function , and instead dynamically generate my LMQL query to use within LangChain.

Something like this -- 
```
llm = "chatgpt"
query = '''lmql
argmax 
    "Write a catchphrase for the following company: {company_name}. [catchphrase]" 
from 
    "chatgpt"
'''
prompt = PromptTemplate(input_variables=["company_name"],template=query)
chain = LLMChain(llm=llm, prompt=prompt)
catchphrase = chain.run(company_name="Rainbow Socks Inc.")
```

**Comment by lbeurerkellner** [comment]
One relevant piece of info here is that `lmql.query` can actually be called with a string of query code, e.g.

write_catch_phrase = lmql.query('''argmax
    "Write a catchphrase for the following company: {company_name}. [catchphrase]" 
from 
    "chatgpt"
''')

However, unfortunately this is not enough here, since the chain abstraction of LC only supports positional arguments and not keyword arguments (as far as I am aware of). However, if you create a LMQL query without a surrounding function, it is not clear how to map positional arguments to query arguments like `company_name`.

As a workaround, I found this works quite well to dynamically construct LC-compatible queries:

```
def make_query(code, args):
    qfct = lmql.query(code)
    qfct.function_context = lmql.FunctionContext(
        args,
        args,
        None
    )
    return qfct

write_catch_phrase = make_query('''argmax
    "Write a catchphrase for the following company: {company_name}. [catchphrase]" 
from 
    "chatgpt"
''', ["company_name"])
```

Overall, I think this should be handled similar to Python though, where positional arguments can also be treated as keyword args, if no more positional parameters remain, making this workaround unnecessary. I will keep and rename this issue accordingly, so we can implement this in the future.

**Comment by praveenv** [comment]
Thanks @lbeurerkellner ! 
Apologies for the potentially dumb follow-up question -- but given your code snippet, how do we transform it into an LLM Chain? 
Given that LLMChain seems to require a `PromptTemplate` (or something derived from `BasePromptTemplate`) I tried the following :
```
prompt = PromptTemplate(template=write_catch_phrase, input_variables=["company_name"])
chain = LLMChain(llm=llm, prompt=prompt)
chain.run("Rainbow Socks. Inc")
```

But I get the following error since template seems to require a `string` input
```
langchain/prompts/prompt.py", line 74, in template_is_valid
    values["template"], values["template_format"], all_inputs
KeyError: 'template'
```

**Comment by praveenv** [comment]
As a workaround , I created a [custom chain](https://python.langchain.com/en/latest/modules/chains/generic/custom_chain.html) class and implemented the `async _acall` that leverages the functions you described above and executes the `LMQL query`. 

```
custom_lmql_chain = MyCustomChain(prompt=PromptTemplate.from_template(query_string), llm=llm)

class MyCustomChain(Chain):
    async def _acall(self, inputs, run_manager):
        # make lmql query from inputs and run
```
  

Based on a few trials, I believe this allows me to include the custom chain as part of larger chains (though the `async API` implementations in LangChain have to become better as you mentioned in the documentation). 

Did you have a better approach in mind?

**Comment by lbeurerkellner** [comment]
Not a dumb question at all :) This is possible and your custom chain solution is how LMQL already implements this out of the box.

LMQL queries constructed via `make_query` above or via decorated functions, are usable as is in LC:

```
from langchain.chains import SimpleSequentialChain
import lmql

def make_query(code, args):
    qfct = lmql.query(code)
    qfct.function_context = lmql.FunctionContext(
        args,
        args,
        None
    )
    return qfct

make_name = make_query('''
    argmax "What is a good name for a company that makes: {product}. [company_name]" from "chatgpt"
''', ["product"])

write_catch_phrase = make_query('''argmax
    "Write a catchphrase for the following company: {company_name}. [catchphrase]" 
from 
    "chatgpt"
''', ["company_name"])


overall_chain = SimpleSequentialChain(chains=[make_name, write_catch_phrase], verbose=True)

# Run the chain specifying only the input variable for the first chain.
catchphrase = overall_chain.run("colorful socks")
print(catchphrase)
```

This way, you don't even need a custom LC chain.
