### ISSUE TITLE
Query from multiple models

### ISSUE THREAD

**Issue by LachlanGray** [eth-sri/lmql#82]
It would be useful to have the ability to use different models in one prompt when different holes have different complexity requirements

**Comment by LachlanGray** [comment]
Maybe a from syntax that is compatible with the ast parser could be
```
from
    with "openai/davinici-003" as smart:
        decoder = beam
        temperature = 0.8
    with "openai/ada-001" as fast:
        decoder = argmax
```
Which could be used in the prompt string with something like

```
query
    "{easy_question}? [fast_answer]"
    "{hard_question}? [smart_answer]"
```
One idea for handling this is to add a new `qstrings` template variable like
```
@dataclass
class ModelTemplateVariable:
    model: str
    name: str
```
And then the compiler could be modified to sandwich `query` calls with `set_model` and `set_decoder` calls in the `_compiled.py` file. The decoder parameters could switch back to whichever configuration you assigned the name "default" so that you can still just do `[completion]` if you are using one model predominantly

**Comment by lbeurerkellner** [comment]
This overlaps in parts with https://github.com/eth-sri/lmql/issues/88, but I think keeping multi-model suport separate makes sense. Another option for multi-model definition, would be to add a simple `lmql.model` function, allowing to specify model parameters like this:

```
from
      lmql.model("openai/davinci-003", decoder="beam", temperature=0.8) as smart
      lmql.model("openai/ada-001", decoder="argmax") as fast
```

This could also work with #88, where a model may also be defined implicitly via e.g. `lmql.set_default_model`.

As in your screenshot on Discord, we should then also think about how users define what model to use per variable. The proposal there was the following:

```
"Some prompt [easy VAR1] and something [hard VAR2]"
```

given the definitions of `easy` and `hard` above.

I think this is an interesting and concise way to express this, and more generally, it may make sense to think about a syntactic construct, extending simple template variable syntax like `[VAR1]` by some annotation like `easy` here. This can be used to specify the model, but other annotations could also be interesting to look at. For instance, one may want to mark a variable as `[stream VAR1]`, to indicate to an output writer that the value of VAR1 should be streamed to the user.
