### ISSUE TITLE
Examples use 3-space tabs, while the playground's default is 4-space

### ISSUE THREAD

**Issue by AnonUser1233** [eth-sri/lmql#90]
I often copy paste or select from some of the examples to try things out. However, it is always slightly annoying to build on the examples because the tabs have 3 spaces, while the playground itself uses 4 spaces for each tab. When I work on it, this often causes the following error to occur:

`RuntimeError: parsing error: unindent does not match any outer indentation level`

Even though completely fixable from my side, it is quite annoying and seems an easy fix.

**Comment by lbeurerkellner** [comment]
Thanks for raising this. I ran into this myself a couple of times already, so it is good to have an issue.

**Comment by lbeurerkellner** [comment]
The web playground now uses 4-space tabs and the next release of LMQL will also change tab size to 4 for the local `lmql playground`. This should make copying straight from the playground much more convenient.
